<?php

namespace AppBundle\Repository;

/**
 * IntroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntroRepository extends \Doctrine\ORM\EntityRepository
{
}
