imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.path.product_images: /uploads/images/article
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
            form:
                fields:
                    - username
                    - email
                    - password
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            list:
                fields:
                    - id
                    - username
                    - email
                    - roles
                    - enabled
        Donate:
            class: AppBundle\Entity\Donate
            form:
                fields:
                    - titre
                    - { property: 'contenu', type: 'ckeditor' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - alt
            list:
                fields:
                    - id
                    - titre
                    - contenu
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
        Article:
            class: AppBundle\Entity\Article
            form:
                fields:
                    - titre
                    - { property: 'contenu', type: 'ckeditor' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'description_image', type: 'text' }
                    - visible
            list:
                fields:
                    - id
                    - titre
                    - contenu
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
                    - visible

            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
        Intro:
            class: AppBundle\Entity\Intro
            form:
                fields:
                    - { property: 'contenu', type: 'ckeditor' }
            list:
                fields:
                    - id
                    - contenu
        Projects:
            class: AppBundle\Entity\Projects
            form:
                fields:
                    - annee
                    - titre
                    - localisation
                    - { property: 'contenu', type: 'ckeditor' }
            list:
                fields:
                    - id
                    - titre
                    - contenu
vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/article'

webfactory_piwik:
    # Required, no default. Must be set to the site id found in the Piwik control panel
    site_id: 1
    # Required, has default. Usually, you only want to include the tracking code in a production environment
    disabled: %kernel.debug%
    # Required. no default. Hostname and path to the piwik host.
    piwik_host: my.piwik.hostname
    # Required, has default. Path to the tracking script on the host.
    tracker_path: "/js/"